In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('matches.csv')

In [28]:
df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [29]:
df.drop(['id', 'dl_applied', 'win_by_runs', 'win_by_wickets' ,'player_of_match', 'umpire1', 'umpire2', 'umpire3', 'date', 'city'], axis=1, inplace=True)

In [30]:
df.drop(['season'],axis=1,inplace=True)

In [32]:
df.drop(['result'],axis=1,inplace=True)

In [33]:

df

,team1,team2,toss_winner,toss_decision,winner,venue
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,Maharashtra Cricket Association Stadium
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,Holkar Cricket Stadium
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium
...,...,...,...,...,...,...
751,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Wankhede Stadium
752,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,Mumbai Indians,M. A. Chidambaram Stadium
753,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,ACA-VDCA Stadium
754,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,ACA-VDCA Stadium
755,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium

In [34]:
df.isnull().sum()

team1            0
team2            0
toss_winner      0
toss_decision    0
winner           4
venue            0
dtype: int64

In [35]:
df.dropna(inplace=True)

In [36]:
df['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [37]:
teams=['Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Kings XI Punjab','Chennai Super Kings', 
       'Rajasthan Royals', 'Delhi Capitals']
df=df[(df['team1'].isin(teams))&(df['team2'].isin(teams))]

In [38]:
df.replace('Delhi Daredevils', 'Delhi Capitals', inplace=True)

/home/hrishikesh/.local/lib/python3.8/site-packages/pandas/core/frame.py:4373: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [39]:
teams=list(enumerate(df['team1'].unique(), start=1))
map_list={value:key for key, value in teams}

In [40]:
map_list

{'Sunrisers Hyderabad': 1,
 'Kolkata Knight Riders': 2,
 'Royal Challengers Bangalore': 3,
 'Kings XI Punjab': 4,
 'Mumbai Indians': 5,
 'Chennai Super Kings': 6,
 'Rajasthan Royals': 7,
 'Delhi Capitals': 8}

In [85]:
df[['team1', 'team2', 'toss_winner', 'winner']]=df[['team1', 'team2', 'toss_winner', 'winner']].apply(lambda x:x.map(map_list), axis=1)

/home/hrishikesh/.local/lib/python3.8/site-packages/pandas/core/frame.py:3062: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [86]:
df=pd.get_dummies(df, columns=['toss_decision'], drop_first=True)

In [100]:
df['team1'] = df['team1'].astype('int64')
df['team2'] = df['team2'].astype('int64')
df['toss_winner'] = df['toss_winner'].astype('int64')
df['winner'] = df['winner'].astype('int64')

In [135]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [136]:
X=df.drop('winner', axis=1)
y=df['winner']
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [137]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [138]:
log_reg=LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.367816091954023

In [139]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.5057471264367817

In [174]:
dt=DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.47126436781609193

In [107]:
import pandas as pd
import numpy as np

In [108]:
df = pd.read_csv('matches.csv')

In [109]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [141]:
from sklearn.ensemble import RandomForestClassifier

In [176]:
rt = RandomForestClassifier()

In [177]:
rt.fit(X_train,y_train)

RandomForestClassifier()

In [179]:
rt.score(X_test,y_test)

0.4482758620689655

In [114]:
df = pd.read_csv('matches.csv')

In [115]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [116]:
df.drop(['id','season','city','result','dl_applied','win_by_wickets','win_by_runs','player_of_match','umpire1','umpire2','umpire3'],axis=1,inplace=True)

In [117]:
df

,date,team1,team2,toss_winner,toss_decision,winner,venue
0,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal"
1,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant,Maharashtra Cricket Association Stadium
2,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,Saurashtra Cricket Association Stadium
3,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,Holkar Cricket Stadium
4,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,M Chinnaswamy Stadium
...,...,...,...,...,...,...,...
751,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,Wankhede Stadium
752,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,Mumbai Indians,M. A. Chidambaram Stadium
753,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,ACA-VDCA Stadium
754,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,ACA-VDCA Stadium
755,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians,Rajiv Gandhi Intl. Cricket Stadium

In [118]:
df.drop(['date','venue'],axis=1,inplace=True)

In [119]:
df

,team1,team2,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore
...,...,...,...,...,...
751,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians
752,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,Mumbai Indians
753,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals
754,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings
755,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians

In [196]:
teams=['Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Kings XI Punjab','Chennai Super Kings', 
       'Rajasthan Royals', 'Delhi Capitals']
df=df[(df['team1'].isin(teams))&(df['team2'].isin(teams))]

In [197]:
df

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
6,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians
7,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab
9,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians
10,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders
...,...,...,...
751,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians
752,Chennai Super Kings,Mumbai Indians,Mumbai Indians
753,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals
754,Delhi Capitals,Chennai Super Kings,Chennai Super Kings
755,Mumbai Indians,Chennai Super Kings,Mumbai Indians

In [122]:
df.replace('Delhi Daredevils', 'Delhi Capitals', inplace=True)

/home/hrishikesh/.local/lib/python3.8/site-packages/pandas/core/frame.py:4373: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [125]:
teams=list(enumerate(df['team1'].unique(), start=1))
map_list={value:key for key, value in teams}

In [123]:
df.isnull().sum()

team1            0
team2            0
toss_winner      0
toss_decision    0
winner           2
dtype: int64

In [124]:
df.dropna()

,team1,team2,toss_winner,toss_decision,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad
6,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians
7,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab
9,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians
10,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
...,...,...,...,...,...
751,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians
752,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,Mumbai Indians
753,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals
754,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings
755,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,Mumbai Indians

In [126]:
df[['team1', 'team2', 'toss_winner', 'winner']]=df[['team1', 'team2', 'toss_winner', 'winner']].apply(lambda x:x.map(map_list), axis=1)

/home/hrishikesh/.local/lib/python3.8/site-packages/pandas/core/frame.py:3062: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [127]:
df

     team1  team2  toss_winner toss_decision  winner
0      1.0    3.0          3.0         field     1.0
6      2.0    5.0          5.0         field     5.0
7      3.0    4.0          3.0           bat     4.0
9      1.0    5.0          5.0         field     5.0
10     4.0    2.0          2.0         field     2.0
..     ...    ...          ...           ...     ...
751    2.0    5.0          5.0         field     5.0
752    6.0    5.0          6.0           bat     5.0
753    1.0    8.0          8.0         field     8.0
754    8.0    6.0          6.0         field     6.0
755    5.0    6.0          5.0           bat     5.0

[437 rows x 5 columns]

In [128]:
df=pd.get_dummies(df, columns=['toss_decision'], drop_first=True)

In [129]:
df.isnull().sum()

team1                  0
team2                  0
toss_winner            0
winner                 2
toss_decision_field    0
dtype: int64

In [130]:
df.dropna(inplace=True)

In [131]:
df

     team1  team2  toss_winner  winner  toss_decision_field
0      1.0    3.0          3.0     1.0                    1
6      2.0    5.0          5.0     5.0                    1
7      3.0    4.0          3.0     4.0                    0
9      1.0    5.0          5.0     5.0                    1
10     4.0    2.0          2.0     2.0                    1
..     ...    ...          ...     ...                  ...
751    2.0    5.0          5.0     5.0                    1
752    6.0    5.0          6.0     5.0                    0
753    1.0    8.0          8.0     8.0                    1
754    8.0    6.0          6.0     6.0                    1
755    5.0    6.0          5.0     5.0                    0

[435 rows x 5 columns]

In [132]:
df.isnull().sum()

team1                  0
team2                  0
toss_winner            0
winner                 0
toss_decision_field    0
dtype: int64

In [133]:
df['team1'] = df['team1'].astype('int64')
df['team2'] = df['team2'].astype('int64')
df['toss_winner'] = df['toss_winner'].astype('int64')
df['winner'] = df['winner'].astype('int64')

In [134]:
df

     team1  team2  toss_winner  winner  toss_decision_field
0        1      3            3       1                    1
6        2      5            5       5                    1
7        3      4            3       4                    0
9        1      5            5       5                    1
10       4      2            2       2                    1
..     ...    ...          ...     ...                  ...
751      2      5            5       5                    1
752      6      5            6       5                    0
753      1      8            8       8                    1
754      8      6            6       6                    1
755      5      6            5       5                    0

[435 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [146]:
X=df.drop('winner', axis=1)
y=df['winner']
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [147]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.4827586206896552

In [149]:
knn.predict(X_test)

array([4, 4, 5, 1, 3, 6, 4, 5, 1, 2, 6, 6, 2, 6, 5, 5, 5, 7, 6, 6, 5, 5,
       2, 4, 5, 6, 6, 5, 2, 5, 6, 3, 2, 6, 6, 1, 4, 6, 7, 2, 6, 6, 2, 2,
       3, 5, 1, 1, 5, 5, 6, 3, 7, 4, 2, 3, 5, 4, 5, 1, 7, 4, 3, 6, 6, 4,
       6, 2, 5, 3, 8, 7, 7, 6, 2, 1, 2, 1, 7, 6, 6, 1, 6, 6, 4, 4, 4])

In [151]:
from sklearn.neural_network import MLPClassifier

In [152]:
mlp = MLPClassifier()

In [153]:
mlp.fit(X_train,y_train)

/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier()

In [154]:
mlp.score(X_test,y_test)

0.3448275862068966

In [158]:
df

     team1  team2  toss_winner  winner  toss_decision_field
0        1      3            3       1                    1
6        2      5            5       5                    1
7        3      4            3       4                    0
9        1      5            5       5                    1
10       4      2            2       2                    1
..     ...    ...          ...     ...                  ...
751      2      5            5       5                    1
752      6      5            6       5                    0
753      1      8            8       8                    1
754      8      6            6       6                    1
755      5      6            5       5                    0

[435 rows x 5 columns]

In [160]:
df1 = df.drop(['toss_winner','winner','toss_decision_field'],axis=1)

In [161]:
df1

     team1  team2
0        1      3
6        2      5
7        3      4
9        1      5
10       4      2
..     ...    ...
751      2      5
752      6      5
753      1      8
754      8      6
755      5      6

[435 rows x 2 columns]

In [162]:
df

     team1  team2  toss_winner  winner  toss_decision_field
0        1      3            3       1                    1
6        2      5            5       5                    1
7        3      4            3       4                    0
9        1      5            5       5                    1
10       4      2            2       2                    1
..     ...    ...          ...     ...                  ...
751      2      5            5       5                    1
752      6      5            6       5                    0
753      1      8            8       8                    1
754      8      6            6       6                    1
755      5      6            5       5                    0

[435 rows x 5 columns]

In [163]:
df2 = df.drop(['toss_winner','toss_decision_field'],axis=1)

In [164]:
df2

     team1  team2  winner
0        1      3       1
6        2      5       5
7        3      4       4
9        1      5       5
10       4      2       2
..     ...    ...     ...
751      2      5       5
752      6      5       5
753      1      8       8
754      8      6       6
755      5      6       5

[435 rows x 3 columns]

In [165]:
X=df2.drop('winner', axis=1)
y=df2['winner']
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [173]:
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.5057471264367817

In [175]:
dt=DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.47126436781609193

In [2]:
import pandas as pd
df = pd.read_csv('matches.csv')

In [3]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [4]:
df.drop(['id','season','toss_winner','toss_decision','result','dl_applied','player_of_match','umpire1','umpire2','umpire3'],axis=1,inplace=True)

In [5]:
df.dropna(inplace=True)

In [6]:
df.drop(['city','date','win_by_runs','win_by_wickets','venue'],axis=1,inplace=True)

In [7]:
df.isnull().sum()

team1     0
team2     0
winner    0
dtype: int64

In [11]:
final = pd.get_dummies(df, prefix=['team1', 'team2'], columns=['team1', 'team2'])

X = final.drop(['winner'], axis=1)
y = final["winner"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [12]:
X

,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Delhi Daredevils,team1_Gujarat Lions,team1_Kings XI Punjab,team1_Kochi Tuskers Kerala,team1_Kolkata Knight Riders,team1_Mumbai Indians,team1_Pune Warriors,...,team2_Kings XI Punjab,team2_Kochi Tuskers Kerala,team2_Kolkata Knight Riders,team2_Mumbai Indians,team2_Pune Warriors,team2_Rajasthan Royals,team2_Rising Pune Supergiant,team2_Rising Pune Supergiants,team2_Royal Challengers Bangalore,team2_Sunrisers Hyderabad
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
752,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
753,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
754,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
755,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, max_features='sqrt', max_depth=20,random_state=0) 
rf.fit(X_train, y_train)
score = rf.score(X_train, y_train)
score2 = rf.score(X_test, y_test)
print("Training set accuracy: ", '%.3f'%(score))
print("Test set accuracy: ", '%.3f'%(score2))

Training set accuracy:  0.716
Test set accuracy:  0.522

In [215]:
dt = DecisionTreeClassifier()

In [216]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [217]:
dt.score(X_test,y_test)

0.5089285714285714

In [14]:
final

,winner,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Delhi Daredevils,team1_Gujarat Lions,team1_Kings XI Punjab,team1_Kochi Tuskers Kerala,team1_Kolkata Knight Riders,team1_Mumbai Indians,...,team2_Kings XI Punjab,team2_Kochi Tuskers Kerala,team2_Kolkata Knight Riders,team2_Mumbai Indians,team2_Pune Warriors,team2_Rajasthan Royals,team2_Rising Pune Supergiant,team2_Rising Pune Supergiants,team2_Royal Challengers Bangalore,team2_Sunrisers Hyderabad
0,Sunrisers Hyderabad,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,Rising Pune Supergiant,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,Kolkata Knight Riders,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,Kings XI Punjab,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,Royal Challengers Bangalore,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Mumbai Indians,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
752,Mumbai Indians,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
753,Delhi Capitals,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
754,Chennai Super Kings,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
755,Mumbai Indians,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [220]:
from sklearn.model_selection import GridSearchCV

In [224]:
rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=100, oob_score = True) 

param_grid = { 
    'n_estimators': [1, 100],
    'max_features': ['auto', 'sqrt', 'log2']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_train, y_train)
print(CV_rfc.best_params_)

/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/model_selection/_split.py:670: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:540: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/home/hrishikesh/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:544: RuntimeWarning: invalid value encountered in true_divide
  decision = (predictions[k] /

{'max_features': 'sqrt', 'n_estimators': 100}

In [6]:
import tabula

# Read PDF into list of DataFrame
df = tabula.read_pdf("schedule.pdf")

'pages' argument isn't specified.Will extract only from page 1 by default.

In [7]:
import tabula

In [9]:
df

[    Match No                                     Match Center  \
 0        1.0       Mumbai Indians (MI) Vs Chennai Super Kings
 1        NaN                                            (CSK)
 2        2.0    Delhi Capitals (DC) Vs Kings XI Punjab (KXIP)
 3        3.0     Royal Challengers Bangalore (RCB) Vs Kolkata
 4        NaN                              Knight Riders (KKR)
 5        4.0     Sun Risers Hyderabad (SRH) Vs Mumbai Indians
 6        NaN                                             (MI)
 7        5.0           Chennai Super Kings (CSK) Vs Rajasthan
 8        NaN                                      Royals (RR)
 9        6.0    Kolkata Knight Riders (KKR) Vs Delhi Capitals
 10       NaN                                             (DC)
 11       7.0   Kings XI Punjab (KXIP) Vs Sun Risers Hyderabad
 12       NaN                                            (SRH)
 13       8.0         Mumbai Indians (MI) Vs Royal Challengers
 14       NaN                                  Bangalore (RCB)
 15       9.0     Rajasthan Royals (RR) Vs Delhi Capitals (DC)
 16      10.0     Kolkata Knight Riders (KKR) Vs Chennai Super
 17       NaN                                      Kings (CSK)
 18      11.0  Royal Challengers Bangalore (RCB) Vs Sun Risers
 19       NaN                                  Hyderabad (SRH)
 20      12.0    Kings XI Punjab (KXIP) Vs Mumbai Indians (MI)
 21      13.0   Rajasthan Royals (RR) Vs Kolkata Knight Riders
 22       NaN                                            (KKR)
 23      14.0         Delhi Capitals (DC) Vs Royal Challengers
 24       NaN                                  Bangalore (RCB)
 25      15.0     Chennai Super Kings (CSK) Vs Kings XI Punjab
 26       NaN                                           (KXIP)
 27      16.0          Sun Risers Hyderabad (SRH) Vs Rajasthan
 28       NaN                                      Royals (RR)

                  Date        Day Time (IST) City
 0   19 September 2020   Saturday    7:30 PM  UAE
 1                 NaN        NaN        NaN  NaN
 2   20 September 2020     Sunday    3:30 PM  UAE
 3   20 September 2020     Sunday    7:30 PM  UAE
 4                 NaN        NaN        NaN  NaN
 5   21 September 2020     Monday    7:30 PM  UAE
 6                 NaN        NaN        NaN  NaN
 7   22 September 2020    Tuesday    7:30 PM  UAE
 8                 NaN        NaN        NaN  NaN
 9   23 September 2020  Wednesday    7:30 PM  UAE
 10                NaN        NaN        NaN  NaN
 11  24 September 2020   Thursday    7:30 PM  UAE
 12                NaN        NaN        NaN  NaN
 13  25 September 2020     Friday    7:30 PM  UAE
 14                NaN        NaN        NaN  NaN
 15  26 September 2020   Saturday    7:30 PM  UAE
 16  27 September 2020     Sunday    3:30 PM  UAE
 17                NaN        NaN        NaN  NaN
 18  27 September 2020     Sunday    7:30 PM  UAE
 19                NaN        NaN        NaN  NaN
 20  28 September 2020     Monday    7:30 PM  UAE
 21  29 September 2020    Tuesday    7:30 PM  UAE
 22                NaN        NaN        NaN  NaN
 23  30 September 2020  Wednesday    7:30 PM  UAE
 24                NaN        NaN        NaN  NaN
 25     1 October 2020   Thursday    7:30 PM  UAE
 26                NaN        NaN        NaN  NaN
 27     2 October 2020     Friday    7:30 PM  UAE
 28                NaN        NaN        NaN  NaN  ]

In [11]:
type(df)

list

In [15]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:@localhost/cricket_prediction', echo=False)

In [16]:
import pandas as pd
fixtures = pd.read_sql('ipl_schedule',engine)

In [17]:
fixtures

,id,team1,date,day,time,city,team2,predicted_winner,original_winner
0,1,Mumbai Indians (MI),19 September 2020,Saturday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Mumbai Indians,
1,2,Delhi Capitals (DC),20 September 2020,Sunday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Kings XI Punjab,
2,3,Sun Risers Hyderabad (SRH),21 September 2020,Monday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Sunrisers Hyderabad,
3,4,Rajasthan Royals (RR),22 September 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Chennai Super Kings,
4,5,Kolkata Knight Riders (KKR),23 September 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Mumbai Indians,
5,6,Kings XI Punjab (KXIP),24 September 2020,Thursday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
6,7,Chennai Super Kings (CSK),25 September 2020,Friday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Chennai Super Kings,
7,8,Kolkata Knight Riders (KKR),26 September 2020,Saturday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Kolkata Knight Riders,
8,9,Rajasthan Royals (RR),27 September 2020,Sunday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Rajasthan Royals,
9,10,Royal Challengers Bangalore (RCB),28 September 2020,Monday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Mumbai Indians,
10,11,Delhi Capitals (DC),29 September 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
11,12,Rajasthan Royals (RR),30 September 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
12,13,Kings XI Punjab (KXIP),01 October 2020,Thursday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Kings XI Punjab,
13,14,Chennai Super Kings (CSK),02 October 2020,Friday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Chennai Super Kings,
14,15,Royal Challengers Bangalore (RCB),03 October 2020,Saturday,3:30 PM IST,2:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
15,16,Delhi Capitals (DC),03 October 2020,Saturday,7:30 PM IST,6:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
16,17,Mumbai Indians (MI),04 October 2020,Sunday,3:30 PM IST,2:00 PM UAE,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
17,18,Kings XI Punjab (KXIP),04 October 2020,Sunday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Kings XI Punjab,
18,19,Royal Challengers Bangalore (RCB),05 October 2020,Monday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Royal Challengers Bangalore,
19,20,Mumbai Indians (MI),06 October 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
20,21,Kolkata Knight Riders (KKR),07 October 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Chennai Super Kings,
21,22,Sun Risers Hyderabad (SRH),08 October 2020,Thursday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Sunrisers Hyderabad,
22,23,Rajasthan Royals (RR),09 October 2020,Friday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Delhi Capitals,
23,24,Kings XI Punjab (KXIP),10 October 2020,Saturday,3:30 PM IST,2:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
24,25,Chennai Super Kings (CSK),10 October 2020,Saturday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Chennai Super Kings,
25,26,Sun Risers Hyderabad (SRH),11 October 2020,Sunday,3:30 PM IST,2:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
26,27,Mumbai Indians (MI),11 October 2020,Sunday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Mumbai Indians,
27,28,Royal Challengers Bangalore (RCB),12 October 2020,Monday,7:30 PM IST,6:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
28,29,Sun Risers Hyderabad (SRH),13 October 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Chennai Super Kings,
29,30,Delhi Capitals (DC),14 October 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
30,31,Royal Challengers Bangalore (RCB),15 October 2020,Thursday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Kings XI Punjab,
31,32,Mumbai Indians (MI),16 October 2020,Friday,7:30 PM IST,6:00 PM UAE,Kolkata Knight Riders (KKR),Mumbai Indians,
32,33,Rajasthan Royals (RR),17 October 2020,Saturday,3:30 PM IST,2:00 PM UAE,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
33,34,Delhi Capitals (DC),17 October 2020,Saturday,7:30 PM IST,6:00 PM UAE,Chennai Super Kings (CSK),Chennai Super Kings,
34,35,Sun Risers Hyderabad (SRH),18 October 2020,Sunday,3:30 PM IST,2:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
35,36,Mumbai Indians (MI),18 October 2020,Sunday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Kings XI Punjab,
36,37,Chennai Super Kings (CSK),19 October 2020,Monday,7:30 PM IST,6:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
37,38,Kings XI Punjab (KXIP),20 October 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Kings XI Punjab,
38,39,Kolkata Knight Riders (KKR),21 October 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Kolkata Knight Riders,
39,40,Rajasthan Royals (RR),22 October 2020,Thursday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Kolkata Knight Riders,
40,41,Chennai Super Kings (CSK),23 October 2020,Friday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Mumbai Indians,
41,42,Kolkata Knight Riders (KKR),24 October 2020,Saturday,3:30 PM IST,2:00 PM UAE,Delhi Capitals (DC),Delhi Capitals,
42,43,Kings XI Punjab (KXIP),24 October 2020,Saturday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
43,44,Royal Challengers Bangalore (RCB),24 October 2020,Sunday,3:30 PM IST,2:00 PM UAE,Chennai Super Kings (CSK),Chennai Super Kings,
44,45,Rajasthan Royals (RR),25 October 2020,Sunday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Mumbai Indians,
45,46,Kolkata Knight Riders (KKR),26 October 2020,Monday,7:30 PM IST,6:00 PM UAE,Kings XI Punjab (KXIP),Kolkata Knight Riders,
46,47,Sun Risers Hyderabad (SRH),27 October 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Delhi Capitals (DC),Delhi Capitals,
47,48,Mumbai Indians (MI),28 October 2020,Wednesday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
48,49,Chennai Super Kings (CSK),29 October 2020,Thursday,7:30 PM IST,6:00 PM UAE,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
49,50,Kings XI Punjab (KXIP),30 October 2020,Friday,7:30 PM IST,6:00 PM UAE,Rajasthan Royals (RR),Kings XI Punjab,
50,51,Delhi Capitals (DC),31 October 2020,Saturday,3:30 PM IST,2:00 PM UAE,Mumbai Indians (MI),Delhi Capitals,
51,52,Royal Challengers Bangalore (RCB),31 October 2020,Saturday,7:30 PM IST,6:00 PM UAE,Sun Risers Hyderabad (SRH),Royal Challengers Bangalore,
52,53,Chennai Super Kings (CSK),01 November 2020,Sunday,3:30 PM IST,2:00 PM UAE,Kings XI Punjab (KXIP),Chennai Super Kings,
53,54,Kolkata Knight Riders (KKR),01 November 2020,Sunday,7:30 PM IST,6:00 PM UAE,Rajasthan Royals (RR),Rajasthan Royals,
54,55,Delhi Capitals (DC),02 November 2020,Monday,7:30 PM IST,6:00 PM UAE,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
55,56,Sun Risers Hyderabad (SRH),03 November 2020,Tuesday,7:30 PM IST,6:00 PM UAE,Mumbai Indians (MI),Sunrisers Hyderabad,

In [18]:
fixtures.drop(['city','time'],axis=1,inplace=True)

In [19]:
fixtures

,id,team1,date,day,team2,predicted_winner,original_winner
0,1,Mumbai Indians (MI),19 September 2020,Saturday,Chennai Super Kings (CSK),Mumbai Indians,
1,2,Delhi Capitals (DC),20 September 2020,Sunday,Kings XI Punjab (KXIP),Kings XI Punjab,
2,3,Sun Risers Hyderabad (SRH),21 September 2020,Monday,Royal Challengers Bangalore (RCB),Sunrisers Hyderabad,
3,4,Rajasthan Royals (RR),22 September 2020,Tuesday,Chennai Super Kings (CSK),Chennai Super Kings,
4,5,Kolkata Knight Riders (KKR),23 September 2020,Wednesday,Mumbai Indians (MI),Mumbai Indians,
5,6,Kings XI Punjab (KXIP),24 September 2020,Thursday,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
6,7,Chennai Super Kings (CSK),25 September 2020,Friday,Delhi Capitals (DC),Chennai Super Kings,
7,8,Kolkata Knight Riders (KKR),26 September 2020,Saturday,Sun Risers Hyderabad (SRH),Kolkata Knight Riders,
8,9,Rajasthan Royals (RR),27 September 2020,Sunday,Kings XI Punjab (KXIP),Rajasthan Royals,
9,10,Royal Challengers Bangalore (RCB),28 September 2020,Monday,Mumbai Indians (MI),Mumbai Indians,
10,11,Delhi Capitals (DC),29 September 2020,Tuesday,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
11,12,Rajasthan Royals (RR),30 September 2020,Wednesday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
12,13,Kings XI Punjab (KXIP),01 October 2020,Thursday,Mumbai Indians (MI),Kings XI Punjab,
13,14,Chennai Super Kings (CSK),02 October 2020,Friday,Sun Risers Hyderabad (SRH),Chennai Super Kings,
14,15,Royal Challengers Bangalore (RCB),03 October 2020,Saturday,Rajasthan Royals (RR),Rajasthan Royals,
15,16,Delhi Capitals (DC),03 October 2020,Saturday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
16,17,Mumbai Indians (MI),04 October 2020,Sunday,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
17,18,Kings XI Punjab (KXIP),04 October 2020,Sunday,Chennai Super Kings (CSK),Kings XI Punjab,
18,19,Royal Challengers Bangalore (RCB),05 October 2020,Monday,Delhi Capitals (DC),Royal Challengers Bangalore,
19,20,Mumbai Indians (MI),06 October 2020,Tuesday,Rajasthan Royals (RR),Rajasthan Royals,
20,21,Kolkata Knight Riders (KKR),07 October 2020,Wednesday,Chennai Super Kings (CSK),Chennai Super Kings,
21,22,Sun Risers Hyderabad (SRH),08 October 2020,Thursday,Kings XI Punjab (KXIP),Sunrisers Hyderabad,
22,23,Rajasthan Royals (RR),09 October 2020,Friday,Delhi Capitals (DC),Delhi Capitals,
23,24,Kings XI Punjab (KXIP),10 October 2020,Saturday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
24,25,Chennai Super Kings (CSK),10 October 2020,Saturday,Royal Challengers Bangalore (RCB),Chennai Super Kings,
25,26,Sun Risers Hyderabad (SRH),11 October 2020,Sunday,Rajasthan Royals (RR),Rajasthan Royals,
26,27,Mumbai Indians (MI),11 October 2020,Sunday,Delhi Capitals (DC),Mumbai Indians,
27,28,Royal Challengers Bangalore (RCB),12 October 2020,Monday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
28,29,Sun Risers Hyderabad (SRH),13 October 2020,Tuesday,Chennai Super Kings (CSK),Chennai Super Kings,
29,30,Delhi Capitals (DC),14 October 2020,Wednesday,Rajasthan Royals (RR),Rajasthan Royals,
30,31,Royal Challengers Bangalore (RCB),15 October 2020,Thursday,Kings XI Punjab (KXIP),Kings XI Punjab,
31,32,Mumbai Indians (MI),16 October 2020,Friday,Kolkata Knight Riders (KKR),Mumbai Indians,
32,33,Rajasthan Royals (RR),17 October 2020,Saturday,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
33,34,Delhi Capitals (DC),17 October 2020,Saturday,Chennai Super Kings (CSK),Chennai Super Kings,
34,35,Sun Risers Hyderabad (SRH),18 October 2020,Sunday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
35,36,Mumbai Indians (MI),18 October 2020,Sunday,Kings XI Punjab (KXIP),Kings XI Punjab,
36,37,Chennai Super Kings (CSK),19 October 2020,Monday,Rajasthan Royals (RR),Rajasthan Royals,
37,38,Kings XI Punjab (KXIP),20 October 2020,Tuesday,Delhi Capitals (DC),Kings XI Punjab,
38,39,Kolkata Knight Riders (KKR),21 October 2020,Wednesday,Royal Challengers Bangalore (RCB),Kolkata Knight Riders,
39,40,Rajasthan Royals (RR),22 October 2020,Thursday,Sun Risers Hyderabad (SRH),Kolkata Knight Riders,
40,41,Chennai Super Kings (CSK),23 October 2020,Friday,Mumbai Indians (MI),Mumbai Indians,
41,42,Kolkata Knight Riders (KKR),24 October 2020,Saturday,Delhi Capitals (DC),Delhi Capitals,
42,43,Kings XI Punjab (KXIP),24 October 2020,Saturday,Sun Risers Hyderabad (SRH),Sunrisers Hyderabad,
43,44,Royal Challengers Bangalore (RCB),24 October 2020,Sunday,Chennai Super Kings (CSK),Chennai Super Kings,
44,45,Rajasthan Royals (RR),25 October 2020,Sunday,Mumbai Indians (MI),Mumbai Indians,
45,46,Kolkata Knight Riders (KKR),26 October 2020,Monday,Kings XI Punjab (KXIP),Kolkata Knight Riders,
46,47,Sun Risers Hyderabad (SRH),27 October 2020,Tuesday,Delhi Capitals (DC),Delhi Capitals,
47,48,Mumbai Indians (MI),28 October 2020,Wednesday,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
48,49,Chennai Super Kings (CSK),29 October 2020,Thursday,Kolkata Knight Riders (KKR),Kolkata Knight Riders,
49,50,Kings XI Punjab (KXIP),30 October 2020,Friday,Rajasthan Royals (RR),Kings XI Punjab,
50,51,Delhi Capitals (DC),31 October 2020,Saturday,Mumbai Indians (MI),Delhi Capitals,
51,52,Royal Challengers Bangalore (RCB),31 October 2020,Saturday,Sun Risers Hyderabad (SRH),Royal Challengers Bangalore,
52,53,Chennai Super Kings (CSK),01 November 2020,Sunday,Kings XI Punjab (KXIP),Chennai Super Kings,
53,54,Kolkata Knight Riders (KKR),01 November 2020,Sunday,Rajasthan Royals (RR),Rajasthan Royals,
54,55,Delhi Capitals (DC),02 November 2020,Monday,Royal Challengers Bangalore (RCB),Royal Challengers Bangalore,
55,56,Sun Risers Hyderabad (SRH),03 November 2020,Tuesday,Mumbai Indians (MI),Sunrisers Hyderabad,

In [20]:
fixtures.drop(['id','day'],axis=1,inplace=True)

In [21]:
pred_set = []

In [22]:
for index, row in fixtures.iterrows():
    pred_set.append({'team1': row['team1'], 'team2': row['team2'], 'winner': None})
        
pred_set = pd.DataFrame(pred_set)
backup_pred_set = pred_set
pred_set.head()

                         team1                              team2 winner
0          Mumbai Indians (MI)          Chennai Super Kings (CSK)   None
1          Delhi Capitals (DC)             Kings XI Punjab (KXIP)   None
2   Sun Risers Hyderabad (SRH)  Royal Challengers Bangalore (RCB)   None
3        Rajasthan Royals (RR)          Chennai Super Kings (CSK)   None
4  Kolkata Knight Riders (KKR)                Mumbai Indians (MI)   None

In [23]:
pred_set

,team1,team2,winner
0,Mumbai Indians (MI),Chennai Super Kings (CSK),None
1,Delhi Capitals (DC),Kings XI Punjab (KXIP),None
2,Sun Risers Hyderabad (SRH),Royal Challengers Bangalore (RCB),None
3,Rajasthan Royals (RR),Chennai Super Kings (CSK),None
4,Kolkata Knight Riders (KKR),Mumbai Indians (MI),None
5,Kings XI Punjab (KXIP),Royal Challengers Bangalore (RCB),None
6,Chennai Super Kings (CSK),Delhi Capitals (DC),None
7,Kolkata Knight Riders (KKR),Sun Risers Hyderabad (SRH),None
8,Rajasthan Royals (RR),Kings XI Punjab (KXIP),None
9,Royal Challengers Bangalore (RCB),Mumbai Indians (MI),None
10,Delhi Capitals (DC),Sun Risers Hyderabad (SRH),None
11,Rajasthan Royals (RR),Kolkata Knight Riders (KKR),None
12,Kings XI Punjab (KXIP),Mumbai Indians (MI),None
13,Chennai Super Kings (CSK),Sun Risers Hyderabad (SRH),None
14,Royal Challengers Bangalore (RCB),Rajasthan Royals (RR),None
15,Delhi Capitals (DC),Kolkata Knight Riders (KKR),None
16,Mumbai Indians (MI),Sun Risers Hyderabad (SRH),None
17,Kings XI Punjab (KXIP),Chennai Super Kings (CSK),None
18,Royal Challengers Bangalore (RCB),Delhi Capitals (DC),None
19,Mumbai Indians (MI),Rajasthan Royals (RR),None
20,Kolkata Knight Riders (KKR),Chennai Super Kings (CSK),None
21,Sun Risers Hyderabad (SRH),Kings XI Punjab (KXIP),None
22,Rajasthan Royals (RR),Delhi Capitals (DC),None
23,Kings XI Punjab (KXIP),Kolkata Knight Riders (KKR),None
24,Chennai Super Kings (CSK),Royal Challengers Bangalore (RCB),None
25,Sun Risers Hyderabad (SRH),Rajasthan Royals (RR),None
26,Mumbai Indians (MI),Delhi Capitals (DC),None
27,Royal Challengers Bangalore (RCB),Kolkata Knight Riders (KKR),None
28,Sun Risers Hyderabad (SRH),Chennai Super Kings (CSK),None
29,Delhi Capitals (DC),Rajasthan Royals (RR),None
30,Royal Challengers Bangalore (RCB),Kings XI Punjab (KXIP),None
31,Mumbai Indians (MI),Kolkata Knight Riders (KKR),None
32,Rajasthan Royals (RR),Royal Challengers Bangalore (RCB),None
33,Delhi Capitals (DC),Chennai Super Kings (CSK),None
34,Sun Risers Hyderabad (SRH),Kolkata Knight Riders (KKR),None
35,Mumbai Indians (MI),Kings XI Punjab (KXIP),None
36,Chennai Super Kings (CSK),Rajasthan Royals (RR),None
37,Kings XI Punjab (KXIP),Delhi Capitals (DC),None
38,Kolkata Knight Riders (KKR),Royal Challengers Bangalore (RCB),None
39,Rajasthan Royals (RR),Sun Risers Hyderabad (SRH),None
40,Chennai Super Kings (CSK),Mumbai Indians (MI),None
41,Kolkata Knight Riders (KKR),Delhi Capitals (DC),None
42,Kings XI Punjab (KXIP),Sun Risers Hyderabad (SRH),None
43,Royal Challengers Bangalore (RCB),Chennai Super Kings (CSK),None
44,Rajasthan Royals (RR),Mumbai Indians (MI),None
45,Kolkata Knight Riders (KKR),Kings XI Punjab (KXIP),None
46,Sun Risers Hyderabad (SRH),Delhi Capitals (DC),None
47,Mumbai Indians (MI),Royal Challengers Bangalore (RCB),None
48,Chennai Super Kings (CSK),Kolkata Knight Riders (KKR),None
49,Kings XI Punjab (KXIP),Rajasthan Royals (RR),None
50,Delhi Capitals (DC),Mumbai Indians (MI),None
51,Royal Challengers Bangalore (RCB),Sun Risers Hyderabad (SRH),None
52,Chennai Super Kings (CSK),Kings XI Punjab (KXIP),None
53,Kolkata Knight Riders (KKR),Rajasthan Royals (RR),None
54,Delhi Capitals (DC),Royal Challengers Bangalore (RCB),None
55,Sun Risers Hyderabad (SRH),Mumbai Indians (MI),None

In [24]:
pred_set = pd.get_dummies(pred_set, prefix=['team1', 'team2'], columns=['team1', 'team2'])

missing_cols = set(final.columns) - set(pred_set.columns)
for c in missing_cols:
    pred_set[c] = 0
pred_set = pred_set[final.columns]


pred_set = pred_set.drop(['winner'], axis=1)
pred_set.head()

,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Delhi Daredevils,team1_Gujarat Lions,team1_Kings XI Punjab,team1_Kochi Tuskers Kerala,team1_Kolkata Knight Riders,team1_Mumbai Indians,team1_Pune Warriors,...,team2_Kings XI Punjab,team2_Kochi Tuskers Kerala,team2_Kolkata Knight Riders,team2_Mumbai Indians,team2_Pune Warriors,team2_Rajasthan Royals,team2_Rising Pune Supergiant,team2_Rising Pune Supergiants,team2_Royal Challengers Bangalore,team2_Sunrisers Hyderabad
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
predictions = rf.predict(pred_set)
for i in range(fixtures.shape[0]):
    print(backup_pred_set.iloc[i, 1] + " and " + backup_pred_set.iloc[i, 0])
    if predictions[i] == 1:
        print("Winner: " + backup_pred_set.iloc[i, 1])
    
    else:
        print("Winner: " + backup_pred_set.iloc[i, 0])
    print("")

Chennai Super Kings (CSK) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Kings XI Punjab (KXIP) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Royal Challengers Bangalore (RCB) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Chennai Super Kings (CSK) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Mumbai Indians (MI) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Royal Challengers Bangalore (RCB) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Delhi Capitals (DC) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Sun Risers Hyderabad (SRH) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Kings XI Punjab (KXIP) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Mumbai Indians (MI) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Sun Risers Hyderabad (SRH) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Kolkata Knight Riders (KKR) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Mumbai Indians (MI) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Sun Risers Hyderabad (SRH) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Rajasthan Royals (RR) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Kolkata Knight Riders (KKR) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Sun Risers Hyderabad (SRH) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Chennai Super Kings (CSK) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Delhi Capitals (DC) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Rajasthan Royals (RR) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Chennai Super Kings (CSK) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Kings XI Punjab (KXIP) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Delhi Capitals (DC) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Kolkata Knight Riders (KKR) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Royal Challengers Bangalore (RCB) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Rajasthan Royals (RR) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Delhi Capitals (DC) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Kolkata Knight Riders (KKR) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Chennai Super Kings (CSK) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Rajasthan Royals (RR) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Kings XI Punjab (KXIP) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Kolkata Knight Riders (KKR) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Royal Challengers Bangalore (RCB) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Chennai Super Kings (CSK) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Kolkata Knight Riders (KKR) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Kings XI Punjab (KXIP) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Rajasthan Royals (RR) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Delhi Capitals (DC) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Royal Challengers Bangalore (RCB) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Sun Risers Hyderabad (SRH) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Mumbai Indians (MI) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Delhi Capitals (DC) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Sun Risers Hyderabad (SRH) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Chennai Super Kings (CSK) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Mumbai Indians (MI) and Rajasthan Royals (RR)
Winner: Rajasthan Royals (RR)

Kings XI Punjab (KXIP) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Delhi Capitals (DC) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

Royal Challengers Bangalore (RCB) and Mumbai Indians (MI)
Winner: Mumbai Indians (MI)

Kolkata Knight Riders (KKR) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Rajasthan Royals (RR) and Kings XI Punjab (KXIP)
Winner: Kings XI Punjab (KXIP)

Mumbai Indians (MI) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Sun Risers Hyderabad (SRH) and Royal Challengers Bangalore (RCB)
Winner: Royal Challengers Bangalore (RCB)

Kings XI Punjab (KXIP) and Chennai Super Kings (CSK)
Winner: Chennai Super Kings (CSK)

Rajasthan Royals (RR) and Kolkata Knight Riders (KKR)
Winner: Kolkata Knight Riders (KKR)

Royal Challengers Bangalore (RCB) and Delhi Capitals (DC)
Winner: Delhi Capitals (DC)

Mumbai Indians (MI) and Sun Risers Hyderabad (SRH)
Winner: Sun Risers Hyderabad (SRH)

In [70]:
rf.score(X_test,y_test)

0.5223214285714286

In [26]:
backup_pred_set

,team1,team2,winner
0,Mumbai Indians (MI),Chennai Super Kings (CSK),None
1,Delhi Capitals (DC),Kings XI Punjab (KXIP),None
2,Sun Risers Hyderabad (SRH),Royal Challengers Bangalore (RCB),None
3,Rajasthan Royals (RR),Chennai Super Kings (CSK),None
4,Kolkata Knight Riders (KKR),Mumbai Indians (MI),None
5,Kings XI Punjab (KXIP),Royal Challengers Bangalore (RCB),None
6,Chennai Super Kings (CSK),Delhi Capitals (DC),None
7,Kolkata Knight Riders (KKR),Sun Risers Hyderabad (SRH),None
8,Rajasthan Royals (RR),Kings XI Punjab (KXIP),None
9,Royal Challengers Bangalore (RCB),Mumbai Indians (MI),None
10,Delhi Capitals (DC),Sun Risers Hyderabad (SRH),None
11,Rajasthan Royals (RR),Kolkata Knight Riders (KKR),None
12,Kings XI Punjab (KXIP),Mumbai Indians (MI),None
13,Chennai Super Kings (CSK),Sun Risers Hyderabad (SRH),None
14,Royal Challengers Bangalore (RCB),Rajasthan Royals (RR),None
15,Delhi Capitals (DC),Kolkata Knight Riders (KKR),None
16,Mumbai Indians (MI),Sun Risers Hyderabad (SRH),None
17,Kings XI Punjab (KXIP),Chennai Super Kings (CSK),None
18,Royal Challengers Bangalore (RCB),Delhi Capitals (DC),None
19,Mumbai Indians (MI),Rajasthan Royals (RR),None
20,Kolkata Knight Riders (KKR),Chennai Super Kings (CSK),None
21,Sun Risers Hyderabad (SRH),Kings XI Punjab (KXIP),None
22,Rajasthan Royals (RR),Delhi Capitals (DC),None
23,Kings XI Punjab (KXIP),Kolkata Knight Riders (KKR),None
24,Chennai Super Kings (CSK),Royal Challengers Bangalore (RCB),None
25,Sun Risers Hyderabad (SRH),Rajasthan Royals (RR),None
26,Mumbai Indians (MI),Delhi Capitals (DC),None
27,Royal Challengers Bangalore (RCB),Kolkata Knight Riders (KKR),None
28,Sun Risers Hyderabad (SRH),Chennai Super Kings (CSK),None
29,Delhi Capitals (DC),Rajasthan Royals (RR),None
30,Royal Challengers Bangalore (RCB),Kings XI Punjab (KXIP),None
31,Mumbai Indians (MI),Kolkata Knight Riders (KKR),None
32,Rajasthan Royals (RR),Royal Challengers Bangalore (RCB),None
33,Delhi Capitals (DC),Chennai Super Kings (CSK),None
34,Sun Risers Hyderabad (SRH),Kolkata Knight Riders (KKR),None
35,Mumbai Indians (MI),Kings XI Punjab (KXIP),None
36,Chennai Super Kings (CSK),Rajasthan Royals (RR),None
37,Kings XI Punjab (KXIP),Delhi Capitals (DC),None
38,Kolkata Knight Riders (KKR),Royal Challengers Bangalore (RCB),None
39,Rajasthan Royals (RR),Sun Risers Hyderabad (SRH),None
40,Chennai Super Kings (CSK),Mumbai Indians (MI),None
41,Kolkata Knight Riders (KKR),Delhi Capitals (DC),None
42,Kings XI Punjab (KXIP),Sun Risers Hyderabad (SRH),None
43,Royal Challengers Bangalore (RCB),Chennai Super Kings (CSK),None
44,Rajasthan Royals (RR),Mumbai Indians (MI),None
45,Kolkata Knight Riders (KKR),Kings XI Punjab (KXIP),None
46,Sun Risers Hyderabad (SRH),Delhi Capitals (DC),None
47,Mumbai Indians (MI),Royal Challengers Bangalore (RCB),None
48,Chennai Super Kings (CSK),Kolkata Knight Riders (KKR),None
49,Kings XI Punjab (KXIP),Rajasthan Royals (RR),None
50,Delhi Capitals (DC),Mumbai Indians (MI),None
51,Royal Challengers Bangalore (RCB),Sun Risers Hyderabad (SRH),None
52,Chennai Super Kings (CSK),Kings XI Punjab (KXIP),None
53,Kolkata Knight Riders (KKR),Rajasthan Royals (RR),None
54,Delhi Capitals (DC),Royal Challengers Bangalore (RCB),None
55,Sun Risers Hyderabad (SRH),Mumbai Indians (MI),None

In [72]:
pred_set

,team1_Chennai Super Kings,team1_Deccan Chargers,team1_Delhi Capitals,team1_Delhi Daredevils,team1_Gujarat Lions,team1_Kings XI Punjab,team1_Kochi Tuskers Kerala,team1_Kolkata Knight Riders,team1_Mumbai Indians,team1_Pune Warriors,...,team2_Kings XI Punjab,team2_Kochi Tuskers Kerala,team2_Kolkata Knight Riders,team2_Mumbai Indians,team2_Pune Warriors,team2_Rajasthan Royals,team2_Rising Pune Supergiant,team2_Rising Pune Supergiants,team2_Royal Challengers Bangalore,team2_Sunrisers Hyderabad
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
a = {"a":[]}

In [76]:
a["a"].append(2)

In [77]:
a

{'a': [2]}

In [78]:
x = pd.DataFrame(a)

In [79]:
x

   a
0  2

In [80]:
table = {"team1":[],"team2":[],"winner":[]}
predictions = rf.predict(pred_set)
for i in range(fixtures.shape[0]):
    table["team1"].append(backup_pred_set.iloc[i,1])
    table["team2"].append(backup_pred_set.iloc[i,0])
    if predictions[i] == 1:
        table["winner"].append(backup_pred_set.iloc[i, 1])
    
    else:
        table["winner"].append(backup_pred_set.iloc[i, 0])
    print("")

In [81]:
table

{'team1': [' Chennai Super Kings (CSK)',
  ' Kings XI Punjab (KXIP)',
  ' Kolkata Knight Riders (KKR)',
  ' Mumbai Indians (MI)',
  ' Rajasthan Royals (RR)',
  ' Delhi Capitals (DC)',
  ' Sun Risers Hyderabad (SRH)',
  ' Royal Challengers Bangalore (RCB)',
  ' Delhi Capitals (DC)',
  ' Chennai Super Kings (CSK)',
  ' Sun Risers Hyderabad (SRH)',
  ' Mumbai Indians (MI)',
  ' Kolkata Knight Riders (KKR)',
  ' Royal Challengers Bangalore (RCB)',
  ' Kings XI Punjab (KXIP)',
  ' Rajasthan Royals (RR)',
  ' Mumbai Indians (MI)',
  ' Chennai Super Kings (CSK)',
  ' Royal Challengers Bangalore (RCB)',
  ' Rajasthan Royals (RR)',
  ' Kolkata Knight Riders (KKR)',
  ' Chennai Super Kings (CSK)',
  ' Rajasthan Royals (RR)',
  ' Kolkata Knight Riders (KKR)',
  ' Sun Risers Hyderabad (SRH)',
  ' Kings XI Punjab (KXIP)',
  ' Sun Risers Hyderabad (SRH)',
  ' Delhi Capitals (DC)',
  ' Kings XI Punjab (KXIP)',
  ' Mumbai Indians (MI)',
  ' Royal Challengers Bangalore (RCB)',
  ' Kolkata Knight Riders (KKR)',
  ' Delhi Capitals (DC)',
  ' Royal Challengers Bangalore (RCB)',
  ' Kolkata Knight Riders (KKR)',
  ' Kings XI Punjab (KXIP)',
  ' Chennai Super Kings (CSK)',
  ' Delhi Capitals (DC)',
  ' Rajasthan Royals (RR)',
  ' Kings XI Punjab (KXIP)',
  ' Sun Risers Hyderabad (SRH)',
  ' Chennai Super Kings (CSK)',
  ' Royal Challengers Bangalore (RCB)',
  ' Mumbai Indians (MI)',
  ' Kolkata Knight Riders (KKR)',
  ' Rajasthan Royals (RR)',
  ' Sun Risers Hyderabad (SRH)',
  ' Delhi Capitals (DC)',
  ' Royal Challengers Bangalore (RCB)',
  ' Mumbai Indians (MI)',
  ' Kings XI Punjab (KXIP)',
  ' Rajasthan Royals (RR)',
  ' Chennai Super Kings (CSK)',
  ' Sun Risers Hyderabad (SRH)',
  ' Delhi Capitals (DC)',
  ' Mumbai Indians (MI)'],
 'team2': ['Mumbai Indians (MI) ',
  'Delhi Capitals (DC) ',
  'Royal Challengers Bangalore (RCB) ',
  'Sun Risers Hyderabad (SRH) ',
  'Chennai Super Kings (CSK) ',
  'Kolkata Knight Riders (KKR) ',
  ' Kings XI Punjab (KXIP) ',
  ' Mumbai Indians (MI) ',
  ' Rajasthan Royals (RR) ',
  'Kolkata Knight Riders (KKR) ',
  ' Royal Challengers Bangalore (RCB) ',
  ' Kings XI Punjab (KXIP) ',
  ' Rajasthan Royals (RR) ',
  'Delhi Capitals (DC) ',
  'Chennai Super Kings (CSK) ',
  'Sun Risers Hyderabad (SRH) ',
  'Kolkata Knight Riders (KKR) ',
  ' Delhi Capitals (DC) ',
  'Kings XI Punjab (KXIP) ',
  'Mumbai Indians (MI) ',
  ' Sun Risers Hyderabad (SRH) ',
  'Kings XI Punjab (KXIP) ',
  'Royal Challengers Bangalore (RCB) ',
  ' Delhi Capitals (DC) ',
  ' Chennai Super Kings (CSK) ',
  'Mumbai Indians (MI) ',
  'Rajasthan Royals (RR) ',
  ' Royal Challengers Bangalore (RCB) ',
  ' Kolkata Knight Riders (KKR) ',
  'Chennai Super Kings (CSK) ',
  'Rajasthan Royals (RR) ',
  'Kings XI Punjab (KXIP) ',
  'Sun Risers Hyderabad (SRH) ',
  'Chennai Super Kings (CSK) ',
  'Mumbai Indians (MI) ',
  ' Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  'Mumbai Indians (MI) ',
  ' Kolkata Knight Riders (KKR) ',
  'Royal Challengers Bangalore (RCB) ',
  'Delhi Capitals (DC) ',
  ' Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  ' Delhi Capitals (DC) ',
  'Chennai Super Kings (CSK) ',
  ' Kings XI Punjab (KXIP) ',
  'Mumbai Indians (MI) ',
  'Chennai Super Kings (CSK) ',
  ' Kolkata Knight Riders (KKR) ',
  'Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  'Delhi Capitals (DC) ',
  'Royal Challengers Bangalore (RCB) ',
  ' Kolkata Knight Riders (KKR) ',
  ' Kings XI Punjab (KXIP) ',
  'Royal Challengers Bangalore (RCB) '],
 'winner': ['Mumbai Indians (MI) ',
  'Delhi Capitals (DC) ',
  'Royal Challengers Bangalore (RCB) ',
  'Sun Risers Hyderabad (SRH) ',
  'Chennai Super Kings (CSK) ',
  'Kolkata Knight Riders (KKR) ',
  ' Kings XI Punjab (KXIP) ',
  ' Mumbai Indians (MI) ',
  ' Rajasthan Royals (RR) ',
  'Kolkata Knight Riders (KKR) ',
  ' Royal Challengers Bangalore (RCB) ',
  ' Kings XI Punjab (KXIP) ',
  ' Rajasthan Royals (RR) ',
  'Delhi Capitals (DC) ',
  'Chennai Super Kings (CSK) ',
  'Sun Risers Hyderabad (SRH) ',
  'Kolkata Knight Riders (KKR) ',
  ' Delhi Capitals (DC) ',
  'Kings XI Punjab (KXIP) ',
  'Mumbai Indians (MI) ',
  ' Sun Risers Hyderabad (SRH) ',
  'Kings XI Punjab (KXIP) ',
  'Royal Challengers Bangalore (RCB) ',
  ' Delhi Capitals (DC) ',
  ' Chennai Super Kings (CSK) ',
  'Mumbai Indians (MI) ',
  'Rajasthan Royals (RR) ',
  ' Royal Challengers Bangalore (RCB) ',
  ' Kolkata Knight Riders (KKR) ',
  'Chennai Super Kings (CSK) ',
  'Rajasthan Royals (RR) ',
  'Kings XI Punjab (KXIP) ',
  'Sun Risers Hyderabad (SRH) ',
  'Chennai Super Kings (CSK) ',
  'Mumbai Indians (MI) ',
  ' Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  'Mumbai Indians (MI) ',
  ' Kolkata Knight Riders (KKR) ',
  'Royal Challengers Bangalore (RCB) ',
  'Delhi Capitals (DC) ',
  ' Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  ' Delhi Capitals (DC) ',
  'Chennai Super Kings (CSK) ',
  ' Kings XI Punjab (KXIP) ',
  'Mumbai Indians (MI) ',
  'Chennai Super Kings (CSK) ',
  ' Kolkata Knight Riders (KKR) ',
  'Rajasthan Royals (RR) ',
  'Sun Risers Hyderabad (SRH) ',
  'Delhi Capitals (DC) ',
  'Royal Challengers Bangalore (RCB) ',
  ' Kolkata Knight Riders (KKR) ',
  ' Kings XI Punjab (KXIP) ',
  'Royal Challengers Bangalore (RCB) ']}

In [82]:
tabel_df = pd.DataFrame(table)

In [83]:
tabel_df

,team1,team2,winner
0,Chennai Super Kings (CSK),Mumbai Indians (MI),Mumbai Indians (MI)
1,Kings XI Punjab (KXIP),Delhi Capitals (DC),Delhi Capitals (DC)
2,Kolkata Knight Riders (KKR),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
3,Mumbai Indians (MI),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
4,Rajasthan Royals (RR),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
5,Delhi Capitals (DC),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
6,Sun Risers Hyderabad (SRH),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
7,Royal Challengers Bangalore (RCB),Mumbai Indians (MI),Mumbai Indians (MI)
8,Delhi Capitals (DC),Rajasthan Royals (RR),Rajasthan Royals (RR)
9,Chennai Super Kings (CSK),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
10,Sun Risers Hyderabad (SRH),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
11,Mumbai Indians (MI),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
12,Kolkata Knight Riders (KKR),Rajasthan Royals (RR),Rajasthan Royals (RR)
13,Royal Challengers Bangalore (RCB),Delhi Capitals (DC),Delhi Capitals (DC)
14,Kings XI Punjab (KXIP),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
15,Rajasthan Royals (RR),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
16,Mumbai Indians (MI),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
17,Chennai Super Kings (CSK),Delhi Capitals (DC),Delhi Capitals (DC)
18,Royal Challengers Bangalore (RCB),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
19,Rajasthan Royals (RR),Mumbai Indians (MI),Mumbai Indians (MI)
20,Kolkata Knight Riders (KKR),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
21,Chennai Super Kings (CSK),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
22,Rajasthan Royals (RR),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
23,Kolkata Knight Riders (KKR),Delhi Capitals (DC),Delhi Capitals (DC)
24,Sun Risers Hyderabad (SRH),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
25,Kings XI Punjab (KXIP),Mumbai Indians (MI),Mumbai Indians (MI)
26,Sun Risers Hyderabad (SRH),Rajasthan Royals (RR),Rajasthan Royals (RR)
27,Delhi Capitals (DC),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
28,Kings XI Punjab (KXIP),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
29,Mumbai Indians (MI),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
30,Royal Challengers Bangalore (RCB),Rajasthan Royals (RR),Rajasthan Royals (RR)
31,Kolkata Knight Riders (KKR),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
32,Delhi Capitals (DC),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
33,Royal Challengers Bangalore (RCB),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
34,Kolkata Knight Riders (KKR),Mumbai Indians (MI),Mumbai Indians (MI)
35,Kings XI Punjab (KXIP),Rajasthan Royals (RR),Rajasthan Royals (RR)
36,Chennai Super Kings (CSK),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
37,Delhi Capitals (DC),Mumbai Indians (MI),Mumbai Indians (MI)
38,Rajasthan Royals (RR),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
39,Kings XI Punjab (KXIP),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
40,Sun Risers Hyderabad (SRH),Delhi Capitals (DC),Delhi Capitals (DC)
41,Chennai Super Kings (CSK),Rajasthan Royals (RR),Rajasthan Royals (RR)
42,Royal Challengers Bangalore (RCB),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
43,Mumbai Indians (MI),Delhi Capitals (DC),Delhi Capitals (DC)
44,Kolkata Knight Riders (KKR),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
45,Rajasthan Royals (RR),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
46,Sun Risers Hyderabad (SRH),Mumbai Indians (MI),Mumbai Indians (MI)
47,Delhi Capitals (DC),Chennai Super Kings (CSK),Chennai Super Kings (CSK)
48,Royal Challengers Bangalore (RCB),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
49,Mumbai Indians (MI),Rajasthan Royals (RR),Rajasthan Royals (RR)
50,Kings XI Punjab (KXIP),Sun Risers Hyderabad (SRH),Sun Risers Hyderabad (SRH)
51,Rajasthan Royals (RR),Delhi Capitals (DC),Delhi Capitals (DC)
52,Chennai Super Kings (CSK),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)
53,Sun Risers Hyderabad (SRH),Kolkata Knight Riders (KKR),Kolkata Knight Riders (KKR)
54,Delhi Capitals (DC),Kings XI Punjab (KXIP),Kings XI Punjab (KXIP)
55,Mumbai Indians (MI),Royal Challengers Bangalore (RCB),Royal Challengers Bangalore (RCB)

In [84]:
import pickle 

pickle.dump(rf, open('matches.pkl','wb'))

In [27]:
new_set = {'team1':['Kolkata Knight Riders(KKR)'],'team2':['Chennai Super Kings']}

In [36]:
new_set = pd.DataFrame(new_set)

In [29]:
new_set

                        team1                team2
0  Kolkata Knight Riders(KKR)  Chennai Super Kings

In [31]:
predictions = rf.predict(pred_set)
for i in range(new_set.shape[0]):
    print(new_set.iloc[i, 1] + " and " + new_set.iloc[i, 0])
    if predictions[i] == 1:
        print("Winner: " + new_set.iloc[i, 1])
    
    else:
        print("Winner: " + new_set.iloc[i, 0])
    print("")

Chennai Super Kings and Kolkata Knight Riders(KKR)
Winner: Kolkata Knight Riders(KKR)

In [32]:
new_set = {'team1':['Mumbai Indians(MI)'],'team2':['Kings XI Punjab(KXIP)']}

In [34]:
predictions = rf.predict(pred_set)
for i in range(new_set.shape[0]):
    print(new_set.iloc[i, 1] + " and " + new_set.iloc[i, 0])
    if predictions[i] == 1:
        print("Winner: " + new_set.iloc[i, 1])
    
    else:
        print("Winner: " + new_set.iloc[i, 0])
    print("")

Kings XI Punjab(KXIP) and Mumbai Indians(MI)
Winner: Mumbai Indians(MI)

In [35]:
new_set = {'team1':['Mumbai Indians(MI)'],'team2':['Kolkata Knight Riders(KKR)']}

In [37]:
predictions = rf.predict(pred_set)
for i in range(new_set.shape[0]):
    print(new_set.iloc[i, 1] + " and " + new_set.iloc[i, 0])
    if predictions[i] == 1:
        print("Winner: " + new_set.iloc[i, 1])
    
    else:
        print("Winner: " + new_set.iloc[i, 0])
    print("")

Kolkata Knight Riders(KKR) and Mumbai Indians(MI)
Winner: Mumbai Indians(MI)